### ISSUE TITLE
Error 57014 while querying Redshift Serverless

### ISSUE THREAD

**Issue by Olaktal** [aws/amazon-redshift-python-driver#150]
Hello !

I have a python function which aims to create a procedure stored in a SQL file (cf see code below).
At the first run, it fails as described below, but it works at the second run.
It's like the execute fails because the cluster is not really UP because it takes time but at the 2nd run it's UP and it works 🤔 

## Driver version

```
2023-03-21 10:17:23,505 DEBUG:{'user': 'XXXX', 'database': 'XXX, 'application_name': '__main__', 'replication': None, 'client_protocol_version': '2', 'driver_version': 'Redshift Python Driver 2.0.910', 'os_version': 'macOS-13.2.1-arm64-arm-64bit'}
```

## Redshift version

```
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.48038
```

## Python version

``` 
▶ poetry run python3 --version
Python 3.9.1
```

## Problem description
1. Expected behaviour: To create the function described.
2. Actual behaviour: Waiting few seconds
3. Error message/stack trace:
```
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '57014', 'M': 'Query cancelled.', 'F': '../src/pg/src/backend/tcop/node_fault_tolerance.c', 'L': '960', 'R': 'NFTSetupSessionStateOnRestore'}
```
4. Any other details that can be helpful:
My code is as follow

```
    LOGGER.info("Connecting To Redshift Serverless")
    with redshift_connector.connect(
        host=setup_host_url(),
        database='dw',
        user=os.environ["REDSHIFT_USER"],
        password=os.environ['REDSHIFT_PASSWORD'],
        is_serverless=True
    ) as conn:
        conn.autocommit = True
        with conn.cursor() as cursor:
            LOGGER.info("Creating function 'process_domain_fhir_reference'")

            with open(f"{PATH_MIGRATION_PROCEDURE}/process_domain_fhir_reference.sql", 'rb') as file:
                raw_sql_file = file.read()
                sql_query = sqlparse.split(raw_sql_file)[0].lstrip().replace("\n", " ")
                LOGGER.info(f"Executing query: \n {sql_query}")
                result = cursor.execute(sql_query)
```

## Python Driver trace logs
```
2023-03-21 10:17:23,763 INFO:Creating function 'process_domain_fhir_reference'
2023-03-21 10:17:23,766 INFO:Executing query: 
 /*  Implement RGDS exception when processing fhir api resources  */  CREATE OR REPLACE function process_domain_fhir_reference (VARCHAR, VARCHAR)   RETURNS VARCHAR STABLE AS $$     SELECT CASE WHEN $1 = 'rgds' AND SPLIT_PART($2, '/', 1) = 'Organization'         THEN 'lifen-' || $2         ELSE    CASE WHEN SPLIT_PART($2, '/', 1) IN ('Practitioner', 'PractitionerRole') THEN $2                 ELSE $1 || '-' || $2  END         END $$ LANGUAGE SQL;
Traceback (most recent call last):
  File "/Users/vincent.martinez/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/redshift_connector/core.py", line 1631, in execute
    ps = cache["ps"][key]
KeyError: ("/*  Implement RGDS exception when processing fhir api resources  */  CREATE OR REPLACE function process_domain_fhir_reference (VARCHAR, VARCHAR)   RETURNS VARCHAR STABLE AS $$     SELECT CASE WHEN $1 = 'rgds' AND SPLIT_PART($2, '/', 1) = 'Organization'         THEN 'lifen-' || $2         ELSE    CASE WHEN SPLIT_PART($2, '/', 1) IN ('Practitioner', 'PractitionerRole') THEN $2                 ELSE $1 || '-' || $2  END         END $$ LANGUAGE SQL;", ())

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/vincent.martinez/Software/data-engineering/.circleci/run_test_materialization.py", line 91, in <module>
    result = cursor.execute(sql_query)
  File "/Users/vincent.martinez/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/Users/vincent.martinez/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/redshift_connector/core.py", line 1701, in execute
    self.handle_messages(cursor)
  File "/Users/vincent.martinez/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '57014', 'M': 'Query cancelled.', 'F': '../src/pg/src/backend/tcop/node_fault_tolerance.c', 'L': '960', 'R': 'NFTSetupSessionStateOnRestore'}
```

Any idea where it comes from ?
As you can see I already set `is_serverless=True` option.
Maybe a retry option would help here ?

Thanks !

**Comment by Brooke-white** [comment]
Hi @Olaktal , thank you for reaching out. Based off the error message provided, it looks like the Redshift serverless instance was unavailable at the time you tried to execute the query. I do not believe the root issue (query cancelation) has to do with the client (redshift-connector) in this case. 

While retry logic in the client could alleviate this issue, I'd recommend to reach out to Redshift customer support so they may investigate why Redshift server canceled the query execution, as it's likely you would see this behavior with other client tools such as JDBC and ODBC as well.
