### ISSUE TITLE
Cannot connect to redshift database when bundled into an executable using pyinstaller

### ISSUE THREAD

**Issue by sambhe** [aws/amazon-redshift-python-driver#166]
## Problem description
Here is my python code:

import redshift_connector
import getpass

usr=input('Enter Redshift username: ')

# Connects to Redshift cluster using AWS credentials
conn = redshift_connector.connect(
    host='<redshift hostname>',
    database='<db name>',
    user=usr,
    password=getpass.getpass(prompt='Enter Redshift Password: ', stream=None)
 )
print('Connected to the RDB database.\n')

This python code code runs fine when I run the python file and connects to the redshift database 

I bundled it into an exe file using pyinstaller --onefile option.

When I run the executable, I get the following error:

_Traceback (most recent call last):
  File "redshift_connector\core.py", line 606, in __init__
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CH_validate_mapping_v2.py", line 22, in <module>
  File "redshift_connector\__init__.py", line 340, in connect
  File "redshift_connector\core.py", line 632, in __init__
redshift_connector.error.InterfaceError: ('communication error', FileNotFoundError(2, 'No such file or directory'))_

What could be the solution for this. I am not sure if it is related to ssl. If I give the parameter ssl=False the python code also then does not work. So it is not an option.

**Comment by Brooke-white** [comment]
Hey @sambhe,

thanks for opening this issue. I'd be interested to see the logging output from redshift-connector. Our project read me has instructions for enabling logging. If you could share those logs with me it would be helpful for analysis. Also I need to know the version of redshift-connector in use so I can figure out what we are doing on line 632 of init. thanks :)

**Comment by sambhe** [comment]
Sure, @Brooke-white. Thanks for the tip. I am going to look at this again in my sprint. I will post you on this then. Thanks.

**Comment by yotoshi** [comment]
I had the exact same problem but setting the parameter "ssl=False" did solve my issue inside the redshift_connector.

**Comment by Brooke-white** [comment]
Thanks for these details, @yotoshi . This makes me think there could be an issue with reading the `redshift-ca-bundle.crt`, which is used for establishing a connection using SSL.

**Comment by Brooke-white** [comment]
if anyone facing this issue could share how they're generating the executable that'd be a great help. Looking at the docs for pyinstaller it seems there are various options that can be used. Knowing that + the OS where the issue faced will help the team identify a fix. thanks :)

**Comment by sambhe** [comment]
Hi @Brooke-white , The connector version I am using is: 2.0.909. I tried the suggestion from @yotoshi but no success. I set it in the in the init file but the error was same as when I was passing the **SSL=False** through the code for the connector. I turned on the logging with the following code:

```
import logging

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)

```

I got the following log, the error given is again FileNotFoundError: 

2023-06-26 14:15:22,130 - redshift_connector - DEBUG - ===================================
2023-06-26 14:15:22,130 - redshift_connector - DEBUG - User provided connection arguments
2023-06-26 14:15:22,130 - redshift_connector - DEBUG - ===================================
2023-06-26 14:15:22,131 - redshift_connector - DEBUG - {'access_key_id': None, 'allow_db_user_override': False, 'app_id': None, 'app_name': 'amazon_aws_redshift', 'application_name': None, 'auth_profile': None, 'auto_create': False, 'client_id': None, 'client_protocol_version': 2, 'client_secret': None, 'cluster_identifier': None, 'credentials_provider': None, 'database_metadata_current_db_only': True, 'db_groups': [], 'db_name': 'rdb', 'db_user': None, 'duration': 900, 'endpoint_url': None, 'force_lowercase': False, 'host': 'fs-reporting-etl-current.c0zbzlztrg9z.eu-west-1.redshift.amazonaws.com', 'iam': False, 'iam_disable_cache': False, 'idp_host': None, 'idp_response_timeout': 120, 'idp_tenant': None, 'idpPort': 443, 'listen_port': 7890, 'login_url': None, 'max_prepared_statements': 1000, 'partner_sp_id': None, 'password': '***', 'port': 5439, 'preferred_role': None, 'principal': None, 'profile': None, 'region': None, 'replication': None, 'role_arn': None, 'role_session_name': None, 'secret_access_key': None, 'session_token': None, 'source_address': None, 'ssl': True, 'ssl_insecure': True, 'sslmode': 'verify-ca', 'tcp_keepalive': True, 'timeout': None, 'unix_sock': None, 'user_name': 'city_77', 'web_identity_token': None, 'provider_name': None, 'scope': '', 'numeric_to_float': False, 'is_serverless': False, 'serverless_acct_id': None, 'serverless_work_group': None, 'group_federation': False, 'is_serverless_host': False, '_is_serverless': False}
2023-06-26 14:15:22,131 - redshift_connector - DEBUG - ===================================
2023-06-26 14:15:22,131 - redshift_connector - DEBUG - ===================================
2023-06-26 14:15:22,131 - redshift_connector - DEBUG - Connection arguments following validation and IAM auth (if applicable)
2023-06-26 14:15:22,132 - redshift_connector - DEBUG - ===================================
2023-06-26 14:15:22,132 - redshift_connector - DEBUG - {'access_key_id': None, 'allow_db_user_override': False, 'app_id': None, 'app_name': 'amazon_aws_redshift', 'application_name': None, 'auth_profile': None, 'auto_create': False, 'client_id': None, 'client_protocol_version': 2, 'client_secret': None, 'cluster_identifier': None, 'credentials_provider': None, 'database_metadata_current_db_only': True, 'db_groups': [], 'db_name': 'rdb', 'db_user': None, 'duration': 900, 'endpoint_url': None, 'force_lowercase': False, 'host': 'fs-reporting-etl-current.c0zbzlztrg9z.eu-west-1.redshift.amazonaws.com', 'iam': False, 'iam_disable_cache': False, 'idp_host': None, 'idp_response_timeout': 120, 'idp_tenant': None, 'idpPort': 443, 'listen_port': 7890, 'login_url': None, 'max_prepared_statements': 1000, 'partner_sp_id': None, 'password': '***', 'port': 5439, 'preferred_role': None, 'principal': None, 'profile': None, 'region': None, 'replication': None, 'role_arn': None, 'role_session_name': None, 'secret_access_key': None, 'session_token': None, 'source_address': None, 'ssl': True, 'ssl_insecure': True, 'sslmode': 'verify-ca', 'tcp_keepalive': True, 'timeout': None, 'unix_sock': None, 'user_name': 'city_77', 'web_identity_token': None, 'provider_name': None, 'scope': '', 'numeric_to_float': False, 'is_serverless': False, 'serverless_acct_id': None, 'serverless_work_group': None, 'group_federation': False, 'is_serverless_host': False, '_is_serverless': False}
2023-06-26 14:15:22,132 - redshift_connector - DEBUG - ===================================
2023-06-26 14:15:22,132 - redshift_connector.cursor - DEBUG - Cursor.paramstyle=named
2023-06-26 14:15:22,992 - redshift_connector.core - DEBUG - ===================================
2023-06-26 14:15:22,992 - redshift_connector.core - DEBUG - Establishing a connection
2023-06-26 14:15:22,993 - redshift_connector.core - DEBUG - {'user': 'city_77', 'database': 'rdb', 'application_name': '__main__', 'replication': None, 'client_protocol_version': '2', 'driver_version': 'Redshift Python Driver 2.0.909', 'os_version': 'Windows-10-10.0.19045-SP0'}
2023-06-26 14:15:22,995 - redshift_connector.core - DEBUG - ===================================
Traceback (most recent call last):
  File "redshift_connector\core.py", line 606, in __init__
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CH_validate_mapping_v2.py", line 30, in <module>
  File "redshift_connector\__init__.py", line 340, in connect
  File "redshift_connector\core.py", line 632, in __init__
redshift_connector.error.InterfaceError: ('communication error', FileNotFoundError(2, 'No such file or directory'))
[32708] Failed to execute script 'CH_validate_mapping_v2' due to unhandled exception!

**Comment by Brooke-white** [comment]
Thanks for this detail, @sambhe . This is indeed failing when attempting to load the SSL certs. [LOC 606](https://github.com/aws/amazon-redshift-python-driver/blob/v2.0.909/redshift_connector/core.py#L606).

As shown in the log, SSL is enabled. Based on the error, I believe disabling SSL i.e. ssl=False should provide a work around, but we need to resolve this certificate loading error so you can use the connector in a secure fashion. 

If you can share the following I can work to reproduce:

1. how the executable is generated using pyinstaller i.e. which options, etc.
2. which platform the executable is generated on
3. which platform the executable is run on

**Comment by vijay-sambhe-dcc** [comment]
@Brooke-white ,  SSL=False did not work for me either.

The normal python code only worked for me with SSL setting left as it was. When it was set to SSL=False, the normal code also never worked. Also when I created an executable, it did not work too with SSL=False or when it was left as it was.

With SSL=False, the following is produced:

```
Traceback (most recent call last):
  File "D:\Vijay\Projects\rdb\CH_validate_mapping_v2.py", line 22, in <module>
    conn = redshift_connector.connect(
  File "C:\Users\51102\AppData\Local\Programs\Python\Python310\lib\site-packages\redshift_connector\__init__.py", line 340, in connect
    return Connection(
  File "C:\Users\51102\AppData\Local\Programs\Python\Python310\lib\site-packages\redshift_connector\core.py", line 710, in __init__
    raise self.error
redshift_connector.error.InterfaceError: {'S': 'FATAL', 'C': '28000', 'M': 'no pg_hba.conf entry for host "::ffff:137.191.238.49", user "city_77", database "rdb", SSL off', 'F': '../src/pg/src/backend/libpq/auth.c', 'L': '470', 'R': 'ClientAuthentication'}

```
Answers to your questions are:

1. how the executable is generated using pyinstaller i.e. which options, etc. => pyinstaller --onefile pythonfilename.py
2. which platform the executable is generated on => Windows 10 64 bit
3. which platform the executable is run on => Windows 10 64 bit (The same machine when the executable was produced and where the normal python code worked)

**Comment by Brooke-white** [comment]
@vijay-sambhe-dcc , could you provide the warnings emitted when running `pyinstaller --onefile`? it should generate to the `build` folder

**Comment by nn-xsce** [comment]
I'm having the same problem and trying to find a solution.

I believe the problem is in the first line of this code in core.py:

path = os.path.abspath(__file__)
if os.name == "nt":
    path = "\\".join(path.split("\\")[:-1]) + "\\files\\redshift-ca-bundle.crt"
else:
    path = "/".join(path.split("/")[:-1]) + "/files/redshift-ca-bundle.crt"

When turned into an executable, os.path.abspath(__file__) will return a different path and therefore one that doesn't exist

**Comment by Brooke-white** [comment]
Hi folks, I messed around with pyinstaller a bit and believe I have found a fix. The issue has to do with redshift-connector's loading of a cert file which is used when establishing the socket (like nn-xsce@ noted above :) ). pyinstaller's docs suggest [when loading data files](https://pyinstaller.org/en/latest/spec-files.html#adding-data-files) the `--add-data` option or a spec file may be used to ensure a file that is accessible and loaded when the executable is run is accessible. When I called pyinstaller as shown below, I was able to run an executable which performs a simple connection test

`scratch_18.py`
```
import redshift_connector
with redshift_connector.connect(
    host='xxx',
    user='awsuser',
    database='dev',
    password='xxx',
    # note SSL is enabled by default
) as conn:
    with conn.cursor() as cursor:
        cursor.execute("select 1;")
        res = cursor.fetchall()
        print(res)
```

```
pyinstaller --add-data "path_to/redshift_connector/files/redshift-ca-bundle.crt:./redshift_connector/files/" --onefile scratch_18.py
```

**Comment by nn-xsce** [comment]
That works for me. Thanks :)

**Comment by Ev2geny** [comment]
I solved this by running **pyinstaller** with the option `--collect_all redshift_connector`

`pyinstaller --collect_all redshift_connector target_file.py`
