### ISSUE TITLE
Parameterized unload throws an error

### ISSUE THREAD

**Issue by GergelyKalmar** [aws/amazon-redshift-python-driver#31]
## Driver version
2.0.877

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.25109

## Client Operating System
Ubuntu 20.04

## Python version
3.8.5

## Table schema
N/A

## Problem description
1. Expected behaviour: An unload is executed successfully when a parameterized expression is used.
2. Actual behaviour: An error is thrown.
3. Error message/stack trace:
```
> python3 test_unload.py
Traceback (most recent call last):
  File "test_unload.py", line 16, in <module>
    cursor.execute(f"""
  File ".../lib/python3.8/site-packages/redshift_connector/cursor.py", line 162, in execute
    self._c.execute(self, operation, args)
  File ".../lib/python3.8/site-packages/redshift_connector/core.py", line 1016, in execute
    self.handle_messages(cursor)
  File ".../lib/python3.8/site-packages/redshift_connector/core.py", line 1172, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "$1"', 'P': '14', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '718', 'R': 'yyerror'}
```

4. Any other details that can be helpful: the test code works when all parameters are hardcoded.

## Python Driver trace logs
N/A

## Reproduction code
`test_unload.py`:
```python
import os

import redshift_connector

conn = redshift_connector.connect(
    host=os.getenv("REDSHIFT_HOST"),
    database=os.getenv("REDSHIFT_DATABASE"),
    user=os.getenv("REDSHIFT_USER"),
    password=os.getenv("REDSHIFT_PASSWORD"),
)

destination = os.getenv("REDSHIFT_UNLOAD_DESTINATION")
role = os.getenv("REDSHIFT_UNLOAD_ROLE")

cursor = conn.cursor()
cursor.execute(f"""
    UNLOAD (%s)
    TO '{destination}'
    IAM_ROLE '{role}'
    PARALLEL OFF
""", ['SELECT id FROM mydb.accounts WHERE id = 0'])
print(cursor.fetchall())
```

**Comment by Brooke-white** [comment]
Hi @GergelyKalmar ,

Thank you for reaching out. I was able to reproduce the behavior you saw using the code snippet included.

Amazon Redshift does not support prepared statements for `UNLOAD`, and therefore `redshift_connector` does not support this functionality.

Amazon Redshift supports prepared statements for `SELECT`, `INSERT`, `UPDATE`, and `DELETE`. See Amazon Redshift [Database Developer Guide](https://docs.aws.amazon.com/redshift/latest/dg/r_PREPARE.html) for more information.

**Comment by GergelyKalmar** [comment]
Hi @Brooke-white, thank you for the response!

Hm, this is interesting because [sqlalchemy-redshift](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift) does in fact use [bound parameters](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/commands.py#L320) for its unload statements and it works just fine (although it uses the PostgreSQL driver under the hood). The unload statement there produces the following SQL:

```
UNLOAD (%(select)s) TO %(unload_location)s
CREDENTIALS %(credentials)s
```

It is a little bit of a problem that we can't use parameters at all in unload statements with this driver – escaping all parameters properly is much harder to do securely than using bound parameters. This opens up a pretty large target area for SQL injection attacks when using user-provided parameters in analytical applications.

**Comment by Brooke-white** [comment]
Hey @GergelyKalmar ,

Yes, this is a strange issue. I've verified our Amazon Redshift JDBC driver does not support using bound parameters for unload statements, which along with the reference I included above [ref](https://docs.aws.amazon.com/redshift/latest/dg/r_PREPARE.html) makes me wonder if psycopg2, the PostgeSQL driver used for sqlachemy-redshift, is doing something differently than redshift_connector when it comes to passing parameters to the server.

I've gone ahead and reached out to our Amazon Redshift server team to gain some clarity on this issue and will report back with our findings. I definitely see benefit in providing end-users the increased security and flexibility to use bound parameters in as many cases as possible :)

**Comment by Brooke-white** [comment]
Hey @GergelyKalmar ,

The Amazon Redshift server team has confirmed that this functionality is not supported. The content in `()` must be a single quote string that contains a query. See [UNLOAD - Amazon Redshift](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html) for more details. 

```
UNLOAD ('select-statement')
TO 's3://object-path/name-prefix'
authorization
[ option [ ... ] ]

where option is
{ [ FORMAT [ AS ] ] CSV | PARQUET
| PARTITION BY ( column_name [, ... ] ) [ INCLUDE ]
| MANIFEST [ VERBOSE ] 
| HEADER           
| DELIMITER [ AS ] 'delimiter-char' 
| FIXEDWIDTH [ AS ] 'fixedwidth-spec'   
| ENCRYPTED [ AUTO ]
| BZIP2  
| GZIP 
| ZSTD
| ADDQUOTES 
| NULL [ AS ] 'null-string'
| ESCAPE
| ALLOWOVERWRITE
| CLEANPATH
| PARALLEL [ { ON | TRUE } | { OFF | FALSE } ]
| MAXFILESIZE [AS] max-size [ MB | GB ] 
| REGION [AS] 'aws-region' }
```

As for how psycopg2 is supporting bound parameters here -- I am unsure, but would assume the server receives the `UNLOAD` statement with a single quote string within the `()`.

I'll discuss with the Amazon Redshift driver team and see what we can do here.

**Comment by GergelyKalmar** [comment]
Hi @Brooke-white, the best solution would be if UNLOAD would allow us to use a sub-query (just like a CREATE TABLE AS expression does) instead of expecting the query as a string (while allowing us to bind parameters too, of course). Right now it would be difficult to avoid SQL injection attacks even if we could bind parameters like sqlalchemy-redshift does (at least in cases where the 'select-statement' query needs to be built during runtime).

See for example this line: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/commands.py#L428, which uses `literal_binds` to parse the query into a string, however, literal_binds is actually not safe to use on expressions with untrusted input (see [docs](https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#rendering-bound-parameters-inline)). If sub-queries were allowed this problem would not arise.

**Comment by djciregethigher** [comment]
``Hello everyone,

this is my first GitHub post, so bare with me. I think I found a solution.

For context, I'm using RedShift with MacOS.

I ran into similar error where I'm trying to enter variables/parameters into a formatted string to create an SQL query, and with that string of text I use Redshift Connector for Python to execute those queries.

I think I found a solution in my case:

so rather than using this syntax:

`
startDate = '2022-01-01'
endDate = '2022-02-01'

string = f""" select * from table where time between {startDate} and {endDate}"""

connector.cursor().execute(string)`

I used:

`
startDate = '2022-01-01'
endDate = '2022-02-01'

string = """ select * from table where time between {} and {}""".format(startDate, endDate)

connector.cursor().execute(string)`

the difference here is that we're using the .format method to construct our query-string rather than the conventional f-strings.

**Comment by Brooke-white** [comment]
Hey @djciregethigher ,

Thank you for sharing your findings and congrats on your first post :). When comparing the output from the two code blocks, it seems to be identical. Could you please help me understand?

```
startDate = '2022-01-01'
endDate = '2022-02-01'

string1 = f""" select * from table where time between {startDate} and {endDate}"""
print(string1)

startDate = '2022-01-01'
endDate = '2022-02-01'

string2 = """ select * from table where time between {0} and {1}""".format(startDate, endDate)
print(string2)

print(string1 == string2)
```

```
>>> select * from table where time between 2022-01-01 and 2022-02-01
>>> select * from table where time between 2022-01-01 and 2022-02-01
>>>True
```

Not sure if this applies to your use case, but redshift_connector supports parameterization without needing to use format strings which can be a bit cleaner and provide protection against sql injection. I've put an example of how to do this below using Redshift [MONTHS_BETWEEN](https://docs.aws.amazon.com/redshift/latest/dg/r_MONTHS_BETWEEN_function.html) function.

```
with redshift_connector.connect(...) as conn:
    with conn.cursor() as cursor:
        cursor.execute("select months_between(%s,%s);", (endDate, startDate))
```

```
>>> ([1.0],)
```

If you continue to experience issue with this or any other redshift_connector functionality feel free to open a [new issue](https://github.com/aws/amazon-redshift-python-driver/issues/new) and we can work to debug/fix any issue at hand :).

**Comment by dschiavu** [comment]
HI @Brooke-white . I've encountered this same issue with the Redshift's UNLOAD statement lacking support for binding parameters into the SELECT query. This represents a significant limitation and opens up a potential SQL injection attack vector for anyone trying to parametrise their UNLOAD statement's queries with user-supplied parameters and values.

Would appreciate an update on this, and especially on what would be the AWS Redshift team's recommended, security risk-free alternative to this functionality?

Thanks.

**Comment by Brooke-white** [comment]
Hi @dschiavu , I have re-raised this request with the Redshift server team. I agree, adding bind parameter support for UNLOAD statements is a great opportunity for improving security and usability. 

At this time, my personal recommendation would be to use what we have available to protect against SQL injection. [This doc](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html) notes many defensive actions we can take. But I do understand best practices and the linked doc prefer bind parameters as a primary defense against SQL injection.

**Comment by dschiavu** [comment]
Thanks for your quick reply @Brooke-white , and thanks for re-raising this issue with the Redshift server team.

While trying to devise a workaround for this, a colleague of mine has thought up a workaround: instead of binding the parameters into the `UNLOAD` query itself (which is not supported by Redshift), we could simply bind them to the inner sub-query inside the UNLOAD's `( )` first (which happens to be a SELECT query - which is probably the most common subquery used within UNLOAD statements by most Redshift users, I'd say) and run this sub-query first, perhaps with a `LIMIT 1` or `1=0` condition, to limit its running time. This would let us use Redshift's prepared statement support (which is indeed supported for SELECT queries) to bind and validate the potentially risky, user-supplied parameters first. 

Subsequently, if the sub-query executed successfully without any errors or exceptions, we could assume that the sub-query is safe, thus allowing us to wrap the sub-query back into the `UNLOAD` parent statement, but this time replacing the bind parameters with actual user-supplied parameters (simply concatenating them), which have now been validated in the previously run `SELECT` query. 

Of course, this workaround assumes that no other parameters would be bound outside of the `UNLOAD`'s query inside the `( )`.

To give an example, say we need to run this query:

```sql
UNLOAD ('SELECT * FROM students WHERE surname = :surname') 
TO 's3://some-bucket/students/' 
IAM_ROLE 'arn:aws:iam::1234567890123:role/MyRedshiftRole'
```

As is, we can't bind `:surname` into this query, this is unsupported for UNLOAD statements. But we can extract the inner query:

```sql
SELECT * FROM students WHERE surname = :surname LIMIT 1
```

... bind the `:surname` parameter, and execute it.

If the query succeeds, we could then wrap it up back into the parent UNLOAD statement, this time removing the bind parameter and replacing it with the user-supplied input directly, knowing that we just validated it successfully:

```sql
UNLOAD ('SELECT * FROM students WHERE surname = "Smith"') 
TO 's3://some-bucket/students/' 
IAM_ROLE 'arn:aws:iam::1234567890123:role/MyRedshiftRole'
```

What is your (and the Redshift server team's) opinion on this workaround? Would you see any potential risks with this two-phased approach?
