### ISSUE TITLE
Malformed column value of type numeric received when using DECIMAL or NUMERIC in redshift query

### ISSUE THREAD

**Issue by dirkgomez** [aws/amazon-redshift-python-driver#61]
## Driver version
2.0.888

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.30840

## Client Operating System
AWS lambda runtime

## Python version
Python 3.8

## Table schema
not necessary

## Problem description
See this bug https://github.com/awslabs/aws-data-wrangler/issues/912, you can take Ulli's query and run it and will receive a stacktrace like this:

```
Traceback (most recent call last):
    ...
    df = wr.redshift.read_sql_query(
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/awswrangler/redshift.py", line 625, in read_sql_query
    return _db_utils.read_sql_query(
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/awswrangler/_databases.py", line 218, in read_sql_query
    return _fetch_all_results(
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/awswrangler/_databases.py", line 194, in _fetch_all_results
    cursor.execute(*cursor_args)
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/redshift_connector/cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/redshift_connector/core.py", line 1275, in execute
    self.handle_messages(cursor)
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/redshift_connector/core.py", line 1355, in handle_messages
    self.message_types[code](self._read(data_len - 4), cursor)
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/redshift_connector/core.py", line 1343, in handle_DATA_ROW
    row.append(desc[0](data, data_idx, vlen, desc[1]))
  File "/Users/dirk/.local/share/virtualenvs/reports-KY0eOm3o/lib/python3.8/site-packages/redshift_connector/utils/type_utils.py", line 282, in numeric_in_binary
    raise Exception("Malformed column value of type numeric received")
Exception: Malformed column value of type numeric received
```
The driver tests for a length of 8 or 16, it's 10 here though.

**Comment by Brooke-white** [comment]
Hi @dirkgomez, thanks for reporting this issue. the team will take a look at this and report our findings shortly.

**Comment by Brooke-white** [comment]
A workaround to this issue for now is to pass the following argument to the `redshift_connector.connect()` method:

`    client_protocol_version=1 `
