### ISSUE TITLE
datetime.timedelta not supported with date math

### ISSUE THREAD

**Issue by rectalogic** [aws/amazon-redshift-python-driver#72]
## Driver version
2.0.902

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.33904

## Client Operating System
Ubuntu 20.04

## Python version
3.8.10

## Problem description
1. Expected behaviour:
   date math would work with datetime.timedelta like it does with psycopg2
2. Actual behaviour:
    timedelta not supported
3. Error message/stack trace:
```
Traceback (most recent call last):
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1004, in make_params
    params.append(self.py_types[typ])
KeyError: <class 'datetime.timedelta'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1007, in make_params
    params.append(self.inspect_funcs[typ](value))
KeyError: <class 'datetime.timedelta'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1123, in execute
    params = self.make_params(args)
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1031, in make_params
    raise NotSupportedError("type " + str(e) + " not mapped to pg type")
redshift_connector.error.NotSupportedError: type <class 'datetime.timedelta'> not mapped to pg type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sqltd.py", line 10, in <module>
    results = engine.execute(statement)
  File "<string>", line 2, in execute
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned
    return fn(*args, **kwargs)
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3146, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/site/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1123, in execute
    params = self.make_params(args)
  File "/site/venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1031, in make_params
    raise NotSupportedError("type " + str(e) + " not mapped to pg type")
sqlalchemy.exc.NotSupportedError: (redshift_connector.error.NotSupportedError) type <class 'datetime.timedelta'> not mapped to pg type
[SQL: SELECT SYSDATE + %s AS anon_1]
[parameters: (datetime.timedelta(days=1),)]
(Background on this error at: https://sqlalche.me/e/14/tw8g)
```
4. Any other details that can be helpful:
This works fine with `redshift+psycopg2` driver, but fails with `redshift+redshift_connector`
Output when using psycopg2 is
```
[(datetime.datetime(2021, 12, 18, 21, 51, 25, 810107),)]
```

## Reproduction code
```python
import datetime

import sqlalchemy as sa

dsn = "redshift+redshift_connector:///?..."  # fails
# dsn = "redshift+psycopg2:///?..."  # works

engine = sa.create_engine(dsn)
statement = sa.select(sa.func.now() + datetime.timedelta(days=1))
results = engine.execute(statement)
print(results.fetchall())
```

**Comment by Brooke-white** [comment]
Hey @rectalogic ,

Thank you for taking the time to open this issue. I believe the fix to support this would be pretty minor. 

Off the top of my head I think we'd just need to add an entry to `type_utils.py_types` for `datetime.timedelta` mapping it to `(TIMESTAMP, FC_BINARY, timestamp_send_integer)`, as well as adding an entry for `datetime.timedelta` to `Cursor.inspect_funcs`, mapping it to the same inspection function used for `datetime`.


I'll get started on a fix and some local testing. I will keep this issue updated with my progress.

**Comment by Brooke-white** [comment]
Hi @rectalogic ,

Support for this feature will be included in our next release, which is set for early January. I'll follow up in the issue once a release has been made. Thanks again for opening this issue and providing the repro!

**Comment by Brooke-white** [comment]
Hi @rectalogic -- thank you for your patience. we've released support for this feature in [2.0.903](https://github.com/aws/amazon-redshift-python-driver/blob/master/CHANGELOG.md#v20903-2022-01-10). Please open a new issue if you see any issue with the use of the datatype`datetime.timedelta`.
