### ISSUE TITLE
Multiple statements execution

### ISSUE THREAD

**Issue by easthy-alterpost** [aws/amazon-redshift-python-driver#82]
## Driver version
Latest

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.34332

## Python version
3.7

## Problem description
1. Expected behaviour: One can execute multi-statements SQL code at once.
2. Actual behaviour: Can't run more than 1 SQL statement at once
3. Error message/stack trace: `cannot insert multiple commands into a prepared statemen`
4. Any other details that can be helpful:
I have many SQL files with codes like this:
```
BEGIN TRANSACTION;

DROP TABLE IF EXISTS _tmp
;
CREATE TEMPORARY TABLE _tmp (
key char(32) DISTKEY,
....
)
DISTSTYLE KEY
SORTKEY(key)
;
INSERT INTO _tmp
SELECT *
   FROM table_2 
       ....
;

INSERT INTO table_3
SELECT MD5(field_1 || ';' || field_2),
               ...
   FROM table_1
      INNER JOIN _tmp
      ON _tmp.key = table.key
WHERE ...
;
END TRANSACTION;
```
I can't split this code into several SQL and execute this sequentially as it will decrease perfomance. I can't even split this code by `;` as this symbol is used in SQL logic

## Python Driver trace logs
```Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 457, in task_test
    ti.run(ignore_task_deps=True, ignore_ti_state=True, test_mode=True)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1637, in run
    session=session,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/redshift.py", line 73, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib/python3.7/site-packages/redshift_connector/cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python3.7/site-packages/redshift_connector/core.py", line 1194, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.7/site-packages/redshift_connector/core.py", line 1358, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '2972', 'R': 'exec_parse_message'}```

**Comment by Brooke-white** [comment]
Hi @easthy-alterpost -- this limitation is due to how redshift_connector executes statements. Please see linked issue #39 for an explanation of why this limitation exists. 

Adding this feature is not currently on our roadmap, so my recommendation would be to preform some pre-processing of the SQL files (i.e. splitting the statements) so they can be executed by redshift_connector. A 3rd party library like [sqlparse](https://pypi.org/project/sqlparse/) could be worth checking out though as you mentioned there are caveats with parsing SQL.

I will pass your feedback along to the Amazon Redshift driver team and see what we can do.

**Comment by Brooke-white** [comment]
closing in favor of #39
