### ISSUE TITLE
Query times out after 10 seconds

### ISSUE THREAD

**Issue by justinmann** [aws/amazon-redshift-python-driver#91]
## Driver version
redshift-connector==2.0.904

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.35649	

## Client Operating System
Docker running Amazon Linux

## Python version
3.0

## Table schema
N/A

## Problem description
Queries timeout after 10 seconds. I am calling Redshift from Airflow 2.2.2 running in Docker.

Same query works fine from Query Editor in AWS Console.

## Python Driver trace logs
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': '\n  -----------------------------------------------\n  error:  timeout expired\n\n  code:      25300\n  context:   \n  query:     0\n  location:  pgclient.cpp:535\n  process:   padbmaster [pid=24962]\n  -----------------------------------------------\n', 'F': '../src/external_catalog/external_catalog_api.cpp', 'L': '926', 'R': 'localize_external_table'}
[2022-02-23, 23:55:21 UTC] {{taskinstance.py:1280}} INFO - Marking task as FAILED. dag_id=dashboard_kpis.media_public, task_id=task_insert_data, execution_date=20220223T235504, start_date=20220223T235509, end_date=20220223T235521
[2022-02-23, 23:55:21 UTC] {{standard_task_runner.py:91}} ERROR - Failed to execute job 60 for task task_insert_data
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1513, in execute
    ps = cache["ps"][key]
KeyError: ("\n            INSERT INTO dashboard_kpis.media_public (\n                WITH public_rolls AS (\n                    SELECT \n                        id AS roll_id,\n                        CASE special_feature WHEN 'personal' THEN TRUE ELSE FALSE END AS is_personal\n                    FROM dispo_prod.dispo_roll\n                    WHERE _public=TRUE\n                ), public_media AS (\n                    SELECT\n                        media_id,\n                        BOOL_AND(is_personal) is_personal_max,\n                        BOOL_OR(is_personal) is_personal_min,\n                        TRUE AS is_public\n                    FROM dispo_prod.dispo_rollmedia public_media\n                    JOIN public_rolls ON public_rolls.roll_id=public_media.roll_id\n                    GROUP BY media_id\n                )\n                SELECT\n                    DATE(created) AS date,\n                    SUM(CASE is_public AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS public_only_count,\n                    SUM(CASE is_public AND is_personal_min WHEN TRUE THEN 1 ELSE 0 END) AS personal_only_count,\n                    SUM(CASE is_public AND is_personal_min AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS personal_and_public_count,\n                    SUM(CASE is_public WHEN TRUE THEN 1 ELSE 0 END) AS public_any_count,\n                    COUNT(*) AS total_count\n                FROM dispo_prod.dispo_media media\n                LEFT JOIN public_media ON public_media.media_id=media.id\n                GROUP BY date\n                ORDER BY date\n            )\n            ", ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1509, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/redshift.py", line 73, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/cursor.py", line 231, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1583, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1851, in handle_messages
    raise self.error

**Comment by Brooke-white** [comment]
Hey @justinmann ,

Thanks for reaching out. As a sanity check, are you able to connect to Amazon Redshift from your docker container using a CLI tool such as PSQL or RSQL? This can help narrow down if there is a connectivity issue here. If you're unable to connect using a CLI tool, you can find some troubleshooting guides [here in the Amazon Redshift docs](https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-refusal-failure-issues.html), something may need to change in the permissions for your cluster.

Otherwise, can you execute **any basic query** via Airflow + the Amazon Redshift provider? e.g. `select 1;`. This can help us see if there is issue with the specific query you want to run.

If this issue is still seen, could you please provide logs using the [instructions noted here](https://github.com/aws/amazon-redshift-python-driver#logging) so our team can research this issue more.

**Comment by Brooke-white** [comment]
Could you please provide logs as described above so we can look into this further?

**Comment by Brooke-white** [comment]
Also, have you tried setting the timeout for your DAG as discussed here? https://stackoverflow.com/questions/57823172/increase-timeout-for-a-particular-dag-in-airflow

**Comment by justinmann** [comment]
I added this to my code:
Log_Format = "%(levelname)s %(asctime)s - %(message)s"

logging.basicConfig(filename = "logfile.log",
                    stream = sys.stdout,
                    filemode = "w",
                    format = Log_Format,
                    level = logging.DEBUG)

logger = logging.getLogger()

Here is the output:
*** Reading local file: /usr/local/airflow/logs/dashboard_kpis.media_public/task_insert_data/2022-02-24T18:33:01.785736+00:00/1.log
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1035}} INFO - Dependencies all met for <TaskInstance: dashboard_kpis.media_public.task_insert_data manual__2022-02-24T18:33:01.785736+00:00 [queued]>
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1035}} INFO - Dependencies all met for <TaskInstance: dashboard_kpis.media_public.task_insert_data manual__2022-02-24T18:33:01.785736+00:00 [queued]>
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1241}} INFO - 
--------------------------------------------------------------------------------
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1242}} INFO - Starting attempt 1 of 1
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1243}} INFO - 
--------------------------------------------------------------------------------
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1262}} INFO - Executing <Task(RedshiftSQLOperator): task_insert_data> on 2022-02-24 18:33:01.785736+00:00
[2022-02-24, 18:33:06 UTC] {{standard_task_runner.py:52}} INFO - Started process 922 to run task
[2022-02-24, 18:33:06 UTC] {{standard_task_runner.py:76}} INFO - Running: ['***', 'tasks', 'run', 'dashboard_kpis.media_public', 'task_insert_data', 'manual__2022-02-24T18:33:01.785736+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/warehouse/dashboard_kpis/media_public.py', '--cfg-path', '/tmp/tmpy6ekdix7', '--error-file', '/tmp/tmprdfy8ucd']
[2022-02-24, 18:33:06 UTC] {{standard_task_runner.py:77}} INFO - Job 67: Subtask task_insert_data
[2022-02-24, 18:33:06 UTC] {{logging_mixin.py:109}} INFO - Running <TaskInstance: dashboard_kpis.media_public.task_insert_data manual__2022-02-24T18:33:01.785736+00:00 [running]> on host dca860dc325a
[2022-02-24, 18:33:06 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-02-24, 18:33:06 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-02-24, 18:33:06 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-02-24, 18:33:06 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:163 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-02-24, 18:33:06 UTC] {{taskinstance.py:1429}} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dashboard_kpis.media_public
AIRFLOW_CTX_TASK_ID=task_insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T18:33:01.785736+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-24T18:33:01.785736+00:00
[2022-02-24, 18:33:06 UTC] {{redshift.py:71}} INFO - Executing statement: ['set statement_timeout to 600000', 'BEGIN TRANSACTION', 'DELETE FROM dashboard_kpis.media_public', "\n            INSERT INTO dashboard_kpis.media_public (\n                WITH public_rolls AS (\n                    SELECT \n                        id AS roll_id,\n                        CASE special_feature WHEN 'personal' THEN TRUE ELSE FALSE END AS is_personal\n                    FROM dispo_prod.dispo_roll\n                    WHERE _public=TRUE\n                ), public_media AS (\n                    SELECT\n                        media_id,\n                        BOOL_AND(is_personal) is_personal_max,\n                        BOOL_OR(is_personal) is_personal_min,\n                        TRUE AS is_public\n                    FROM dispo_prod.dispo_rollmedia public_media\n                    JOIN public_rolls ON public_rolls.roll_id=public_media.roll_id\n                    GROUP BY media_id\n                )\n                SELECT\n                    DATE(created) AS date,\n                    SUM(CASE is_public AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS public_only_count,\n                    SUM(CASE is_public AND is_personal_min WHEN TRUE THEN 1 ELSE 0 END) AS personal_only_count,\n                    SUM(CASE is_public AND is_personal_min AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS personal_and_public_count,\n                    SUM(CASE is_public WHEN TRUE THEN 1 ELSE 0 END) AS public_any_count,\n                    COUNT(*) AS total_count\n                FROM dispo_prod.dispo_media media\n                LEFT JOIN public_media ON public_media.media_id=media.id\n                GROUP BY date\n                ORDER BY date\n            )\n            ", 'COMMIT TRANSACTION']
[2022-02-24, 18:33:06 UTC] {{base.py:79}} INFO - Using connection to: id: redshift_default. Host: dispo-redshift.cgtsokzvp48s.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: warehouse, Login: awsuser, Password: ***, extra: {}
[2022-02-24, 18:33:07 UTC] {{dbapi.py:225}} INFO - Running statement: set statement_timeout to 600000, parameters: None
[2022-02-24, 18:33:07 UTC] {{dbapi.py:225}} INFO - Running statement: BEGIN TRANSACTION, parameters: None
[2022-02-24, 18:33:07 UTC] {{dbapi.py:225}} INFO - Running statement: DELETE FROM dashboard_kpis.media_public, parameters: None
[2022-02-24, 18:33:07 UTC] {{dbapi.py:233}} INFO - Rows affected: 0
[2022-02-24, 18:33:07 UTC] {{dbapi.py:225}} INFO - Running statement: 
            INSERT INTO dashboard_kpis.media_public (
                WITH public_rolls AS (
                    SELECT 
                        id AS roll_id,
                        CASE special_feature WHEN 'personal' THEN TRUE ELSE FALSE END AS is_personal
                    FROM dispo_prod.dispo_roll
                    WHERE _public=TRUE
                ), public_media AS (
                    SELECT
                        media_id,
                        BOOL_AND(is_personal) is_personal_max,
                        BOOL_OR(is_personal) is_personal_min,
                        TRUE AS is_public
                    FROM dispo_prod.dispo_rollmedia public_media
                    JOIN public_rolls ON public_rolls.roll_id=public_media.roll_id
                    GROUP BY media_id
                )
                SELECT
                    DATE(created) AS date,
                    SUM(CASE is_public AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS public_only_count,
                    SUM(CASE is_public AND is_personal_min WHEN TRUE THEN 1 ELSE 0 END) AS personal_only_count,
                    SUM(CASE is_public AND is_personal_min AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS personal_and_public_count,
                    SUM(CASE is_public WHEN TRUE THEN 1 ELSE 0 END) AS public_any_count,
                    COUNT(*) AS total_count
                FROM dispo_prod.dispo_media media
                LEFT JOIN public_media ON public_media.media_id=media.id
                GROUP BY date
                ORDER BY date
            )
            , parameters: None
[2022-02-24, 18:33:18 UTC] {{taskinstance.py:1703}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1513, in execute
    ps = cache["ps"][key]
KeyError: ("\n            INSERT INTO dashboard_kpis.media_public (\n                WITH public_rolls AS (\n                    SELECT \n                        id AS roll_id,\n                        CASE special_feature WHEN 'personal' THEN TRUE ELSE FALSE END AS is_personal\n                    FROM dispo_prod.dispo_roll\n                    WHERE _public=TRUE\n                ), public_media AS (\n                    SELECT\n                        media_id,\n                        BOOL_AND(is_personal) is_personal_max,\n                        BOOL_OR(is_personal) is_personal_min,\n                        TRUE AS is_public\n                    FROM dispo_prod.dispo_rollmedia public_media\n                    JOIN public_rolls ON public_rolls.roll_id=public_media.roll_id\n                    GROUP BY media_id\n                )\n                SELECT\n                    DATE(created) AS date,\n                    SUM(CASE is_public AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS public_only_count,\n                    SUM(CASE is_public AND is_personal_min WHEN TRUE THEN 1 ELSE 0 END) AS personal_only_count,\n                    SUM(CASE is_public AND is_personal_min AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS personal_and_public_count,\n                    SUM(CASE is_public WHEN TRUE THEN 1 ELSE 0 END) AS public_any_count,\n                    COUNT(*) AS total_count\n                FROM dispo_prod.dispo_media media\n                LEFT JOIN public_media ON public_media.media_id=media.id\n                GROUP BY date\n                ORDER BY date\n            )\n            ", ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1509, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/redshift.py", line 73, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/cursor.py", line 231, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1583, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1851, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': '\n  -----------------------------------------------\n  error:  timeout expired\n\n  code:      25300\n  context:   \n  query:     0\n  location:  pgclient.cpp:535\n  process:   padbmaster [pid=14049]\n  -----------------------------------------------\n', 'F': '../src/external_catalog/external_catalog_api.cpp', 'L': '926', 'R': 'localize_external_table'}
[2022-02-24, 18:33:18 UTC] {{taskinstance.py:1280}} INFO - Marking task as FAILED. dag_id=dashboard_kpis.media_public, task_id=task_insert_data, execution_date=20220224T183301, start_date=20220224T183306, end_date=20220224T183318
[2022-02-24, 18:33:18 UTC] {{standard_task_runner.py:91}} ERROR - Failed to execute job 67 for task task_insert_data
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1513, in execute
    ps = cache["ps"][key]
KeyError: ("\n            INSERT INTO dashboard_kpis.media_public (\n                WITH public_rolls AS (\n                    SELECT \n                        id AS roll_id,\n                        CASE special_feature WHEN 'personal' THEN TRUE ELSE FALSE END AS is_personal\n                    FROM dispo_prod.dispo_roll\n                    WHERE _public=TRUE\n                ), public_media AS (\n                    SELECT\n                        media_id,\n                        BOOL_AND(is_personal) is_personal_max,\n                        BOOL_OR(is_personal) is_personal_min,\n                        TRUE AS is_public\n                    FROM dispo_prod.dispo_rollmedia public_media\n                    JOIN public_rolls ON public_rolls.roll_id=public_media.roll_id\n                    GROUP BY media_id\n                )\n                SELECT\n                    DATE(created) AS date,\n                    SUM(CASE is_public AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS public_only_count,\n                    SUM(CASE is_public AND is_personal_min WHEN TRUE THEN 1 ELSE 0 END) AS personal_only_count,\n                    SUM(CASE is_public AND is_personal_min AND NOT is_personal_max WHEN TRUE THEN 1 ELSE 0 END) AS personal_and_public_count,\n                    SUM(CASE is_public WHEN TRUE THEN 1 ELSE 0 END) AS public_any_count,\n                    COUNT(*) AS total_count\n                FROM dispo_prod.dispo_media media\n                LEFT JOIN public_media ON public_media.media_id=media.id\n                GROUP BY date\n                ORDER BY date\n            )\n            ", ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1509, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/redshift.py", line 73, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/cursor.py", line 231, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1583, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib64/python3.7/site-packages/redshift_connector/core.py", line 1851, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': '\n  -----------------------------------------------\n  error:  timeout expired\n\n  code:      25300\n  context:   \n  query:     0\n  location:  pgclient.cpp:535\n  process:   padbmaster [pid=14049]\n  -----------------------------------------------\n', 'F': '../src/external_catalog/external_catalog_api.cpp', 'L': '926', 'R': 'localize_external_table'}
[2022-02-24, 18:33:18 UTC] {{local_task_job.py:154}} INFO - Task exited with return code 1
[2022-02-24, 18:33:18 UTC] {{local_task_job.py:264}} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-24, 18:33:18 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2022-02-24, 18:33:18 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)

**Comment by justinmann** [comment]
I have tried:
1) execution_timeout=timedelta(seconds=600) in the DAG operator
2) "set statement_timeout to 600000" in the SQL commands sent to Redshift

**Comment by Brooke-white** [comment]
Hi @justinmann ,

Following up to see if you're still experiencing this issue.

**Comment by Brooke-white** [comment]
I'll be closing this out as I haven't heard back. Please re-open if you're still seeing issue here.
